

module.exports = {
    userInfo: {
        extra: {
            now: 1521601500000
        },
        status_code: 0,
        user: {
            activity: {
                digg_count: 0,
                use_music_count: 0
            },
            authority_status: 0,
            avatar_larger: {
                uri: "c1500084b30927d65e2",
                url_list: [
                    "https://p1.pstatp.com/aweme/1080x1080/c1500084b30927d65e2.jpeg",
                    "https://pb3.pstatp.com/aweme/1080x1080/c1500084b30927d65e2.jpeg",
                    "https://pb3.pstatp.com/aweme/1080x1080/c1500084b30927d65e2.jpeg"
                ]
            },
            avatar_medium: {
                uri: "c1500084b30927d65e2",
                url_list: [
                    "https://p1.pstatp.com/aweme/720x720/c1500084b30927d65e2.jpeg",
                    "https://pb3.pstatp.com/aweme/720x720/c1500084b30927d65e2.jpeg",
                    "https://pb3.pstatp.com/aweme/720x720/c1500084b30927d65e2.jpeg"
                ]
            },
            avatar_thumb: {
                uri: "c1500084b30927d65e2",
                url_list: [
                    "https://p1.pstatp.com/aweme/100x100/c1500084b30927d65e2.jpeg",
                    "https://pb3.pstatp.com/aweme/100x100/c1500084b30927d65e2.jpeg",
                    "https://pb3.pstatp.com/aweme/100x100/c1500084b30927d65e2.jpeg"
                ]
            },
            aweme_count: 120,
            bind_phone: "#",
            birthday: "2016-09-15",
            commerce_user_level: 0,
            constellation: 6,
            custom_verify: "抖音短视频官方账号",
            enterprise_verify_reason: "",
            favoriting_count: 151,
            fb_expire_time: 0,
            follow_status: 0,
            follower_count: 13757119,
            followers_detail: [
                {
                    app_name: "aweme",
                    apple_id: "1142110895",
                    download_url: "https://d.douyin.com/JsvN/",
                    fans_count: 13757081,
                    icon: "http://p3.pstatp.com/origin/50ec00079b64de2050dc",
                    name: "抖音",
                    open_url: "snssdk1128://user/profile/6796248446?",
                    package_name: "com.ss.android.ugc.aweme"
                },
                {
                    app_name: "news_article",
                    apple_id: "529092160",
                    download_url: "https://d.toutiao.com/YjjY/",
                    fans_count: 8365,
                    icon: "http://p3.pstatp.com/origin/50ed00079a1b6b8d1fb1",
                    name: "头条",
                    open_url: "snssdk143://profile?uid=59016042836?",
                    package_name: "com.ss.android.article.news"
                },
                {
                    app_name: "live_stream",
                    apple_id: "1086047750",
                    download_url: "http://d.huoshanzhibo.com/eFvB/",
                    fans_count: 403599,
                    icon: "http://p3.pstatp.com/origin/551900041a7e00ec86ca",
                    name: "火山",
                    open_url: "snssdk1112://profile?id=6796248446",
                    package_name: "com.ss.android.ugc.live"
                }
            ],
            following_count: 138,
            gender: 2,
            has_activity_medal: false,
            has_facebook_token: false,
            has_twitter_token: false,
            has_youtube_token: false,
            hide_location: false,
            hide_search: false,
            is_ad_fake: false,
            is_binded_weibo: true,
            is_block: false,
            is_verified: true,
            live_verify: 0,
            location: "",
            mplatform_followers_count: 14169045,
            need_recommend: 0,
            nickname: "抖音小助手",
            original_musician: {
                digg_count: 0,
                music_count: 0,
                music_used_count: 0
            },
            room_id: 0,
            school_name: "",
            school_poi_id: "",
            school_type: 0,
            share_info: {
                share_desc: "在抖音，记录美好生活",
                share_image_url: {
                    uri: "6fe7000356269cfaf8a2",
                    url_list: [
                        "http://p1.pstatp.com/obj/6fe7000356269cfaf8a2",
                        "http://pb3.pstatp.com/obj/6fe7000356269cfaf8a2",
                        "http://pb3.pstatp.com/obj/6fe7000356269cfaf8a2"
                    ]
                },
                share_qrcode_url: {
                    uri: "2bda0053b4bbf955b0dd",
                    url_list: [
                        "http://p9.pstatp.com/obj/2bda0053b4bbf955b0dd",
                        "http://pb1.pstatp.com/obj/2bda0053b4bbf955b0dd",
                        "http://pb3.pstatp.com/obj/2bda0053b4bbf955b0dd"
                    ]
                },
                share_title: "快来加入抖音，让你发现最有趣的我！",
                share_url: "https://www.douyin.com/share/user/6796248446",
                share_weibo_desc: "在抖音，记录美好生活"
            },
            shield_comment_notice: 0,
            shield_digg_notice: 0,
            shield_follow_notice: 0,
            short_id: "52",
            signature: "",
            special_lock: 0,
            star_use_new_download: false,
            story_count: 0,
            story_open: false,
            sync_to_toutiao: 1,
            total_favorited: 16647887,
            tw_expire_time: 0,
            uid: "6796248446",
            unique_id: "douyin",
            verification_type: 1,
            verify_info: "",
            weibo_name: "抖音短视频",
            weibo_schema: "sinaweibo://userinfo?uid=6020086612",
            weibo_url: "https://m.weibo.cn/u/6020086612",
            weibo_verify:
                "微博认证: 北京微播视界科技有限公司火山小视频官方微博",
            with_commerce_entry: false,
            youtube_expire_time: 0
        }
    },
    followerList: {
        extra: {
            logid: "201803211102120100140581343785D2",
            now: 1521601332522,
            fatal_item_ids: []
        },
        has_more: true,
        status_code: 0,
        followers: [
            {
                share_qrcode_uri: "6cc3000b52e052617128",
                avatar_larger: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/6c53000a60132f7ec5d5"
                    ],
                    uri: ""
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "594002502",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/6c53000a60132f7ec5d5"
                    ],
                    uri: ""
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 0,
                star_use_new_download: true,
                school_poi_id: "",
                weibo_schema: "",
                uid: "79768757055",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1521114034,
                verify_info: "",
                constellation: 0,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/6c53000a60132f7ec5d5"
                    ],
                    uri: ""
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "",
                is_ad_fake: false,
                nickname: "貝",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "6722002ec877d8f9f680",
                avatar_larger: {
                    url_list: [
                        "https://p1.pstatp.com/thumb/6c4d0004067a94dca30b"
                    ],
                    uri: ""
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "578849648",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p1.pstatp.com/thumb/6c4d0004067a94dca30b"
                    ],
                    uri: ""
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 2,
                star_use_new_download: true,
                school_poi_id: "",
                weibo_schema: "",
                uid: "94726534978",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1520432500,
                verify_info: "",
                constellation: 0,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p1.pstatp.com/thumb/6c4d0004067a94dca30b"
                    ],
                    uri: ""
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "",
                is_ad_fake: false,
                nickname: "妞、妞",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "49eb0009a1cffed5231c",
                avatar_larger: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/1080x1080/46bb00397200e2986310.jpeg",
                        "https://pb9.pstatp.com/aweme/1080x1080/46bb00397200e2986310.jpeg",
                        "https://pb3.pstatp.com/aweme/1080x1080/46bb00397200e2986310.jpeg"
                    ],
                    uri: "46bb00397200e2986310"
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "128176789",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/100x100/46bb00397200e2986310.jpeg",
                        "https://pb9.pstatp.com/aweme/100x100/46bb00397200e2986310.jpeg",
                        "https://pb3.pstatp.com/aweme/100x100/46bb00397200e2986310.jpeg"
                    ],
                    uri: "46bb00397200e2986310"
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 2,
                star_use_new_download: false,
                school_poi_id: "",
                weibo_schema: "",
                uid: "74970164070",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1510912955,
                verify_info: "",
                constellation: 1,
                community_discipline_status: 0,
                has_register_notice: 1,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/720x720/46bb00397200e2986310.jpeg",
                        "https://pb9.pstatp.com/aweme/720x720/46bb00397200e2986310.jpeg",
                        "https://pb3.pstatp.com/aweme/720x720/46bb00397200e2986310.jpeg"
                    ],
                    uri: "46bb00397200e2986310"
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "1992-03-25",
                is_ad_fake: false,
                nickname: "可可粉",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "46bb00397200e2986310",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "216a002e599bcc472d54",
                avatar_larger: {
                    url_list: [
                        "https://tva3.sinaimg.cn/crop.0.0.996.996.50/bfd8b458jw8fbo7a85k6rj20ro0rodhg.jpg"
                    ],
                    uri: ""
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "17400678",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://tva3.sinaimg.cn/crop.0.0.996.996.50/bfd8b458jw8fbo7a85k6rj20ro0rodhg.jpg"
                    ],
                    uri: ""
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 0,
                star_use_new_download: false,
                school_poi_id: "",
                weibo_schema: "",
                uid: "60923528999",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1495587722,
                verify_info: "",
                constellation: 0,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://tva3.sinaimg.cn/crop.0.0.996.996.50/bfd8b458jw8fbo7a85k6rj20ro0rodhg.jpg"
                    ],
                    uri: ""
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "",
                is_ad_fake: false,
                nickname: "肉多多wx",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "5ade0018a28cb5bd9aa3",
                avatar_larger: {
                    url_list: [
                        "https://p1.pstatp.com/aweme/1080x1080/5add0006d4119c736f21.jpeg",
                        "https://pb3.pstatp.com/aweme/1080x1080/5add0006d4119c736f21.jpeg",
                        "https://pb3.pstatp.com/aweme/1080x1080/5add0006d4119c736f21.jpeg"
                    ],
                    uri: "5add0006d4119c736f21"
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "276888094",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p1.pstatp.com/aweme/100x100/5add0006d4119c736f21.jpeg",
                        "https://pb3.pstatp.com/aweme/100x100/5add0006d4119c736f21.jpeg",
                        "https://pb3.pstatp.com/aweme/100x100/5add0006d4119c736f21.jpeg"
                    ],
                    uri: "5add0006d4119c736f21"
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 0,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 2,
                star_use_new_download: false,
                school_poi_id: "",
                weibo_schema: "",
                uid: "73305559493",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1517237244,
                verify_info: "",
                constellation: 10,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p1.pstatp.com/aweme/720x720/5add0006d4119c736f21.jpeg",
                        "https://pb3.pstatp.com/aweme/720x720/5add0006d4119c736f21.jpeg",
                        "https://pb3.pstatp.com/aweme/720x720/5add0006d4119c736f21.jpeg"
                    ],
                    uri: "5add0006d4119c736f21"
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "1996-01-09",
                is_ad_fake: false,
                nickname: "mF.r",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "5add0006d4119c736f21",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "5fdc0006d3d373ec4d36",
                avatar_larger: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/5d4b0019fe2ce64e7b1c"
                    ],
                    uri: ""
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "330561224",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/5d4b0019fe2ce64e7b1c"
                    ],
                    uri: ""
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 0,
                star_use_new_download: false,
                school_poi_id: "",
                weibo_schema: "",
                uid: "92220573040",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1517981098,
                verify_info: "",
                constellation: 0,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/5d4b0019fe2ce64e7b1c"
                    ],
                    uri: ""
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "",
                is_ad_fake: false,
                nickname: "喵小爷__33",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "330a000db445d0563124",
                avatar_larger: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/36420019b637af80f1b1"
                    ],
                    uri: ""
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "64070774",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/36420019b637af80f1b1"
                    ],
                    uri: ""
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 1,
                star_use_new_download: false,
                school_poi_id: "",
                weibo_schema: "",
                uid: "67228334235",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1503582951,
                verify_info: "",
                constellation: 0,
                community_discipline_status: 0,
                has_register_notice: 1,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/36420019b637af80f1b1"
                    ],
                    uri: ""
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "",
                is_ad_fake: false,
                nickname: "阿准。",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "5fea00131d636f7b63d3",
                avatar_larger: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/65840037582c829584b1"
                    ],
                    uri: ""
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "343439445",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/65840037582c829584b1"
                    ],
                    uri: ""
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 0,
                star_use_new_download: true,
                school_poi_id: "",
                weibo_schema: "",
                uid: "92865939895",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1518408102,
                verify_info: "",
                constellation: 0,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/65840037582c829584b1"
                    ],
                    uri: ""
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "",
                is_ad_fake: false,
                nickname: "37.5^C",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "6f94000479a29d4a7476",
                avatar_larger: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/719e0015f5e3d66b3216"
                    ],
                    uri: ""
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "610087918",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/719e0015f5e3d66b3216"
                    ],
                    uri: ""
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 1,
                star_use_new_download: true,
                school_poi_id: "",
                weibo_schema: "",
                uid: "95749939142",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1521563028,
                verify_info: "",
                constellation: 3,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p3.pstatp.com/thumb/719e0015f5e3d66b3216"
                    ],
                    uri: ""
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "1998-05-21",
                is_ad_fake: false,
                nickname: "久涩ˇ",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "6f8a0023538da8dbda8b",
                avatar_larger: {
                    url_list: ["https://p0.pstatp.com/origin/3791/5035712059"],
                    uri: ""
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "606017440",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: ["https://p0.pstatp.com/origin/3791/5035712059"],
                    uri: ""
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 2,
                star_use_new_download: true,
                school_poi_id: "",
                weibo_schema: "",
                uid: "95641952740",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1521446095,
                verify_info: "",
                constellation: 3,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: ["https://p0.pstatp.com/origin/3791/5035712059"],
                    uri: ""
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "1991-06-13",
                is_ad_fake: false,
                nickname: "小龍",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "5adb00029d0de38f5145",
                avatar_larger: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/1080x1080/6724000765c1be0b05ef.jpeg",
                        "https://pb9.pstatp.com/aweme/1080x1080/6724000765c1be0b05ef.jpeg",
                        "https://pb3.pstatp.com/aweme/1080x1080/6724000765c1be0b05ef.jpeg"
                    ],
                    uri: "6724000765c1be0b05ef"
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "268020512",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/100x100/6724000765c1be0b05ef.jpeg",
                        "https://pb9.pstatp.com/aweme/100x100/6724000765c1be0b05ef.jpeg",
                        "https://pb3.pstatp.com/aweme/100x100/6724000765c1be0b05ef.jpeg"
                    ],
                    uri: "6724000765c1be0b05ef"
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 2,
                star_use_new_download: false,
                school_poi_id: "",
                weibo_schema: "",
                uid: "86626200349",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1516857449,
                verify_info: "",
                constellation: 7,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/720x720/6724000765c1be0b05ef.jpeg",
                        "https://pb9.pstatp.com/aweme/720x720/6724000765c1be0b05ef.jpeg",
                        "https://pb3.pstatp.com/aweme/720x720/6724000765c1be0b05ef.jpeg"
                    ],
                    uri: "6724000765c1be0b05ef"
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "2000-10-13",
                is_ad_fake: false,
                nickname: "抹茶味的颖婆婆",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "6724000765c1be0b05ef",
                signature: "确认过眼神  我遇上对的人",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "5fe80024c95296b87348",
                avatar_larger: {
                    url_list: [
                        "https://p1.pstatp.com/aweme/1080x1080/6723000569c23e631bfa.jpeg",
                        "https://pb3.pstatp.com/aweme/1080x1080/6723000569c23e631bfa.jpeg",
                        "https://pb3.pstatp.com/aweme/1080x1080/6723000569c23e631bfa.jpeg"
                    ],
                    uri: "6723000569c23e631bfa"
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "344197031",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p1.pstatp.com/aweme/100x100/6723000569c23e631bfa.jpeg",
                        "https://pb3.pstatp.com/aweme/100x100/6723000569c23e631bfa.jpeg",
                        "https://pb3.pstatp.com/aweme/100x100/6723000569c23e631bfa.jpeg"
                    ],
                    uri: "6723000569c23e631bfa"
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 0,
                star_use_new_download: true,
                school_poi_id: "",
                weibo_schema: "",
                uid: "92885038698",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1518422539,
                verify_info: "",
                constellation: 0,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p1.pstatp.com/aweme/720x720/6723000569c23e631bfa.jpeg",
                        "https://pb3.pstatp.com/aweme/720x720/6723000569c23e631bfa.jpeg",
                        "https://pb3.pstatp.com/aweme/720x720/6723000569c23e631bfa.jpeg"
                    ],
                    uri: "6723000569c23e631bfa"
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "",
                is_ad_fake: false,
                nickname: "再也没有",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "6723000569c23e631bfa",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "6f88002cb5d4c50648af",
                avatar_larger: {
                    url_list: [
                        "https://thirdqq.qlogo.cn/qqapp/1105602870/218430CF874126957F91C655872758C7/40"
                    ],
                    uri: ""
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "601339681",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://thirdqq.qlogo.cn/qqapp/1105602870/218430CF874126957F91C655872758C7/40"
                    ],
                    uri: ""
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 0,
                star_use_new_download: true,
                school_poi_id: "",
                weibo_schema: "",
                uid: "76567968409",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1521299289,
                verify_info: "",
                constellation: 0,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://thirdqq.qlogo.cn/qqapp/1105602870/218430CF874126957F91C655872758C7/40"
                    ],
                    uri: ""
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "",
                is_ad_fake: false,
                nickname: "一猫",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "46b7000e2f0e9a428f3c",
                avatar_larger: {
                    url_list: [
                        "https://q.qlogo.cn/qqapp/1105602870/309C30969ADF84B09A24664C2C5578D4/40"
                    ],
                    uri: ""
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "121009670",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://q.qlogo.cn/qqapp/1105602870/309C30969ADF84B09A24664C2C5578D4/40"
                    ],
                    uri: ""
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 2,
                star_use_new_download: false,
                school_poi_id: "",
                weibo_schema: "",
                uid: "75243598754",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1510241721,
                verify_info: "",
                constellation: 1,
                community_discipline_status: 0,
                has_register_notice: 1,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://q.qlogo.cn/qqapp/1105602870/309C30969ADF84B09A24664C2C5578D4/40"
                    ],
                    uri: ""
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "2001-04-10",
                is_ad_fake: false,
                nickname: "安诺",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "",
                signature: "qq3482609885",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "49e7000bba6eb44f975f",
                avatar_larger: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/1080x1080/6f8f0015f028abd63542.jpeg",
                        "https://pb9.pstatp.com/aweme/1080x1080/6f8f0015f028abd63542.jpeg",
                        "https://pb3.pstatp.com/aweme/1080x1080/6f8f0015f028abd63542.jpeg"
                    ],
                    uri: "6f8f0015f028abd63542"
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "128508660",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/100x100/6f8f0015f028abd63542.jpeg",
                        "https://pb9.pstatp.com/aweme/100x100/6f8f0015f028abd63542.jpeg",
                        "https://pb3.pstatp.com/aweme/100x100/6f8f0015f028abd63542.jpeg"
                    ],
                    uri: "6f8f0015f028abd63542"
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 2,
                star_use_new_download: false,
                school_poi_id: "",
                weibo_schema: "",
                uid: "76210772953",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1510924874,
                verify_info: "",
                constellation: 2,
                community_discipline_status: 0,
                has_register_notice: 1,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/720x720/6f8f0015f028abd63542.jpeg",
                        "https://pb9.pstatp.com/aweme/720x720/6f8f0015f028abd63542.jpeg",
                        "https://pb3.pstatp.com/aweme/720x720/6f8f0015f028abd63542.jpeg"
                    ],
                    uri: "6f8f0015f028abd63542"
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "2002-05-06",
                is_ad_fake: false,
                nickname: "丫头",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "6f8f0015f028abd63542",
                signature: "你若毁我现在，我定废你未来",
                weibo_verify: "",
                unique_id: "dlmm082609102016"
            },
            {
                share_qrcode_uri: "65a50022c78e9aa08bcf",
                avatar_larger: {
                    url_list: [
                        "https://p1.pstatp.com/aweme/1080x1080/6cbf001dec3da9374747.jpeg",
                        "https://pb3.pstatp.com/aweme/1080x1080/6cbf001dec3da9374747.jpeg",
                        "https://pb3.pstatp.com/aweme/1080x1080/6cbf001dec3da9374747.jpeg"
                    ],
                    uri: "6cbf001dec3da9374747"
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "364240506",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p1.pstatp.com/aweme/100x100/6cbf001dec3da9374747.jpeg",
                        "https://pb3.pstatp.com/aweme/100x100/6cbf001dec3da9374747.jpeg",
                        "https://pb3.pstatp.com/aweme/100x100/6cbf001dec3da9374747.jpeg"
                    ],
                    uri: "6cbf001dec3da9374747"
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 2,
                star_use_new_download: true,
                school_poi_id: "",
                weibo_schema: "",
                uid: "93357906007",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1518949970,
                verify_info: "",
                constellation: 8,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p1.pstatp.com/aweme/720x720/6cbf001dec3da9374747.jpeg",
                        "https://pb3.pstatp.com/aweme/720x720/6cbf001dec3da9374747.jpeg",
                        "https://pb3.pstatp.com/aweme/720x720/6cbf001dec3da9374747.jpeg"
                    ],
                    uri: "6cbf001dec3da9374747"
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "1995-10-27",
                is_ad_fake: false,
                nickname: "。Echo",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "6cbf001dec3da9374747",
                signature: "谦谦。魔道。汉服。王者。腐。(ಡωಡ) ",
                weibo_verify: "",
                unique_id: "echo_joker520"
            },
            {
                share_qrcode_uri: "38cc00363a1eaaef1582",
                avatar_larger: {
                    url_list: [
                        "https://p1.pstatp.com/thumb/3efd0002f69b69a1cff9"
                    ],
                    uri: ""
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "91090457",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p1.pstatp.com/thumb/3efd0002f69b69a1cff9"
                    ],
                    uri: ""
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 1,
                star_use_new_download: false,
                school_poi_id: "",
                weibo_schema: "",
                uid: "71803322155",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1507639671,
                verify_info: "",
                constellation: 12,
                community_discipline_status: 0,
                has_register_notice: 1,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p1.pstatp.com/thumb/3efd0002f69b69a1cff9"
                    ],
                    uri: ""
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "2000-03-12",
                is_ad_fake: false,
                nickname: "垃圾",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "5fd900079e6439f9a474",
                avatar_larger: {
                    url_list: ["https://p1.pstatp.com/thumb/3795/3033762272"],
                    uri: ""
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "324889071",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: ["https://p1.pstatp.com/thumb/3795/3033762272"],
                    uri: ""
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 2,
                star_use_new_download: false,
                school_poi_id: "",
                weibo_schema: "",
                uid: "73313142231",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1517847661,
                verify_info: "",
                constellation: 8,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: ["https://p1.pstatp.com/thumb/3795/3033762272"],
                    uri: ""
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "1987-11-02",
                is_ad_fake: false,
                nickname: "细雨",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "49e70046e0fe40e0c528",
                avatar_larger: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/1080x1080/6f88000f6689476ae647.jpeg",
                        "https://pb9.pstatp.com/aweme/1080x1080/6f88000f6689476ae647.jpeg",
                        "https://pb3.pstatp.com/aweme/1080x1080/6f88000f6689476ae647.jpeg"
                    ],
                    uri: "6f88000f6689476ae647"
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "102994570",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/100x100/6f88000f6689476ae647.jpeg",
                        "https://pb9.pstatp.com/aweme/100x100/6f88000f6689476ae647.jpeg",
                        "https://pb3.pstatp.com/aweme/100x100/6f88000f6689476ae647.jpeg"
                    ],
                    uri: "6f88000f6689476ae647"
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 2,
                star_use_new_download: false,
                school_poi_id: "",
                weibo_schema: "",
                uid: "72757055952",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1508592042,
                verify_info: "",
                constellation: 1,
                community_discipline_status: 0,
                has_register_notice: 0,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/720x720/6f88000f6689476ae647.jpeg",
                        "https://pb9.pstatp.com/aweme/720x720/6f88000f6689476ae647.jpeg",
                        "https://pb3.pstatp.com/aweme/720x720/6f88000f6689476ae647.jpeg"
                    ],
                    uri: "6f88000f6689476ae647"
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "1992-04-15",
                is_ad_fake: false,
                nickname: "长不大的草莓_",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "6f88000f6689476ae647",
                signature: "不伤心，不等待，不期待，不假设。",
                weibo_verify: "",
                unique_id: ""
            },
            {
                share_qrcode_uri: "42de00111b8763d562ee",
                avatar_larger: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/1080x1080/6f8e001eba57a48a40f4.jpeg",
                        "https://pb9.pstatp.com/aweme/1080x1080/6f8e001eba57a48a40f4.jpeg",
                        "https://pb3.pstatp.com/aweme/1080x1080/6f8e001eba57a48a40f4.jpeg"
                    ],
                    uri: "6f8e001eba57a48a40f4"
                },
                enterprise_verify_reason: "",
                original_music_qrcode: null,
                story_open: false,
                live_verify: 0,
                short_id: "115838970",
                account_region: "",
                reflow_page_gid: 0,
                avatar_thumb: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/100x100/6f8e001eba57a48a40f4.jpeg",
                        "https://pb9.pstatp.com/aweme/100x100/6f8e001eba57a48a40f4.jpeg",
                        "https://pb3.pstatp.com/aweme/100x100/6f8e001eba57a48a40f4.jpeg"
                    ],
                    uri: "6f8e001eba57a48a40f4"
                },
                is_binded_weibo: false,
                is_verified: true,
                hide_search: false,
                risk_flag: 0,
                with_commerce_entry: false,
                school_name: "",
                custom_verify: "",
                special_lock: 1,
                shield_comment_notice: 0,
                hide_location: false,
                gender: 2,
                star_use_new_download: false,
                school_poi_id: "",
                weibo_schema: "",
                uid: "74582216831",
                bind_phone: "",
                weibo_url: "",
                weibo_name: "",
                commerce_user_level: 0,
                create_time: 1509776441,
                verify_info: "",
                constellation: 0,
                community_discipline_status: 0,
                has_register_notice: 1,
                need_recommend: 1,
                shield_digg_notice: 0,
                update_before: 0,
                verification_type: 1,
                room_id: 0,
                avatar_medium: {
                    url_list: [
                        "https://p3.pstatp.com/aweme/720x720/6f8e001eba57a48a40f4.jpeg",
                        "https://pb9.pstatp.com/aweme/720x720/6f8e001eba57a48a40f4.jpeg",
                        "https://pb3.pstatp.com/aweme/720x720/6f8e001eba57a48a40f4.jpeg"
                    ],
                    uri: "6f8e001eba57a48a40f4"
                },
                authority_status: 0,
                enterprise_verify: false,
                reflow_page_uid: 0,
                birthday: "",
                is_ad_fake: false,
                nickname: "❤好久不见",
                shield_follow_notice: 0,
                original_music_cover: null,
                follow_status: 0,
                region: "CN",
                school_type: 0,
                avatar_uri: "6f8e001eba57a48a40f4",
                signature: "",
                weibo_verify: "",
                unique_id: ""
            }
        ],
        max_time: 1521601194,
        min_time: 1521601147,
        total: 403599,
        myself_user_id: "0"
    }
};